# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = '$python$character$directory$git_branchâœ˜ '

# Inserts a blank line between shell prompts
add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character]
success_symbol = '[â†’](bold green)'
error_symbol = '[â†’](bold red)'
#âœâ†’
# Disable the package module, hiding it from the prompt completely

[git_branch]
format = '[git:\([$branch](bold red)\) ]($style)'
symbol = ''
style = 'bold yellow'

[package]
disabled = true

[python]
style = 'bold green'
format = '[(ğŸ\($virtualenv\) )]($style)'
